feat: markdown table links check
okp4/awesome pull request #33
Opened 2023-07-05 20:13 UTC by alexandrglaznyov

This pull request includes the following changes:

- Moved JavaScript-related files (index.js, package.json, package-lock.json) to ./github/scripts directory.
- Added a new GitHub Action named update-service-status-badges.yml.
- Configured manual triggering of the GitHub Action using workflow_dispatch.
- Enhanced the functionality of the action by adding a cron schedule.
- Added the commit message to "docs: update url service status badges".
- Added a script that edits the README.md file to check link status based on the URL column in each service table
- Added a helper directory with corresponding code for link checking
- Updated the README.md file to separate the Services table into multiple tables (RPC, API, gRPC, etc.) for better visibility of individual service statuses
- Added a status column to the Block Explorers, Documentation / Guides, and Dashboards tables for monitoring link functionality

2023-07-06 07:15 UTC, ccamel requested changes
Looks awesome! :+1:  Just some minor changes requested on my side - it would so great it if you could take them into consideration.

2023-07-06 07:15 UTC, ccamel commented on .github/workflows/update-service-status-badges.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-22.04
```

2023-07-06 07:15 UTC, ccamel commented on README.md
> +- [Code of conduct](https://github.com/okp4/.github/blob/main/CODE_OF_CONDUCT.md)
`MD047/single-trailing-newline`- Files should end with a single newline character

```suggestion
- [Code of conduct](https://github.com/okp4/.github/blob/main/CODE_OF_CONDUCT.md)

```

2023-07-06 07:28 UTC, ccamel commented on .github/workflows/update-service-status-badges.yml
> +
workflows/update-service-status-badges.yml:11:1: [error] trailing spaces (trailing-spaces)

```suggestion

```

2023-07-06 14:39 UTC, ccamel approved these changes
LGTM! Thanks for your great contribution.

2023-07-07 07:28 UTC, amimart approved these changes
Looks good! Thanks a lot 🙏

2023-07-07 08:16 UTC, bdeneux approved these changes
Very nice ! Thanks 👍

Just one question about `package.json ` but otherwise it seems very good ! Thanks.

2023-07-07 08:16 UTC, bdeneux commented on .github/scripts/package.json
> +  "homepage": "https://github.com/alexandrglaznyov/okp4-README#readme",
Shouldn't we put the correct repo url here? @ccamel  

```suggestion
    "url": "git+https://github.com/okp4/awesome.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/okp4/awesome/issues"
  },
  "homepage": "https://github.com/okp4/awesome#readme",
```

2023-07-07 09:53 UTC, ccamel commented
Everything looks good! Time to merge. :smile:

2023-07-07 09:53 UTC, merged